name = "0xjimmy-fusion/cardano-resolver"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project '0xjimmy-fusion/cardano-resolver'"

[repository]
user = "0xjimmy-fusion"
project = "cardano-resolver"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
